# Generated by Django 5.2.4 on 2025-07-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_unpublish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unpublish',
            new_name='is_publish',
        ),
    ]
