# Generated by Django 5.2.4 on 2025-07-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_unpublish_product_is_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_publish',
            new_name='unpublish',
        ),
    ]
